### ISSUE TITLE
docs on obtaining a session key

### ISSUE THREAD

**Issue by nick-youngblut** [hcevikdotpy/claude-pyrojects#1]
From the README:

> Refer to [this](https://github.com/KoushikNavuluri/Claude-API?tab=readme-ov-file#usage) on how to get your session key.

https://github.com/KoushikNavuluri/Claude-API/blob/main/README.md does not refer to a "session key". By "session key", do you mean "cookie of claude.ai"?

**Comment by hcevikdotpy** [comment]
@nick-youngblut Yes, look for the "sessionKey" key inside the cookie and copy it's value

**Comment by nick-youngblut** [comment]
Thanks for clarifying!
